import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const presetSource = readFileSync(resolve(root, "src/presets/partner-presets.ts"), "utf8");
const mainSource = readFileSync(resolve(root, "src/main.ts"), "utf8");

const bundled = [
  "/* Generated by scripts/build.mjs. Do not edit directly. */",
  presetSource.replace(/^export\s+/gm, ""),
  mainSource.replace(/^import\s+\{\s*PARTNER_PRESETS\s*\}\s+from\s+['\"].\/presets\/partner-presets['\"];?\s*$/m, ""),
].join("\n\n");

mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist/main.js"), bundled);
