import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const mainSource = readFileSync(resolve(root, "src/main.ts"), "utf8");
const presetSource = readFileSync(resolve(root, "src/presets/partner-presets.ts"), "utf8")
  .replace("export const PARTNER_PRESETS", "const PARTNER_PRESETS");

const bundled = [
  "/* Generated by scripts/build.mjs. Do not edit directly. */",
  presetSource,
  mainSource,
].join("\n\n");

mkdirSync(resolve(root, "dist"), { recursive: true });
writeFileSync(resolve(root, "dist/main.js"), bundled);
copyFileSync(resolve(root, "src/ui.html"), resolve(root, "dist/ui.html"));
